name: .NET

on:
  push:
    branches: [ main ]
    paths:
      - 'Magic8HeadService/**'

jobs:
  build:

    runs-on: lab-pi

    steps:
    - uses: actions/checkout@v3
    - run: env
    - run: sudo systemctl stop Magic8HeadService
    - run: dotnet publish Magic8HeadService/Magic8HeadService.csproj -c Release -o /srv/Magic8HeadService/
    - run: sudo systemctl start Magic8HeadService
